#!/usr/bin/env python3
"""Close the complementation-connectivity gap in the extended sweeps.

A connected example H of high regular degree D (or high degree window) has a
low-degree complement H-bar with the same card-type and orbit counts, but
H-bar may be DISCONNECTED, so the connected-only low-degree sweeps miss it.
Since the complement of a disconnected graph is always connected, it
suffices to additionally test every disconnected graph on n vertices whose
degrees lie in the low slice: each is a disjoint union of connected
components in the same slice.

This script enumerates all such unions (component multisets, components
generated by geng per size), and runs the same exact card-type/orbit test
(stage2 logic inlined) on each union. A WITNESS here means its (connected)
complement is an example for the Kourovka problem.

Slices closed: regular d, parts >= d+1, n in {13, 14} (n=12 is subsumed by
the full order-12 census); degree windows [a, a+1], a = 2..5, n = 13.
"""
from __future__ import annotations

import itertools
import subprocess
import sys
from pathlib import Path

_HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(_HERE / "vendor"))
_VV = _HERE / f"vendor{sys.version_info.major}{sys.version_info.minor}"
if _VV.is_dir():
    sys.path.insert(0, str(_VV))
import pynauty  # noqa: E402

GENG = "/opt/homebrew/bin/geng"


def parse_g6(s: bytes):
    n = s[0] - 63
    adj = [[] for _ in range(n)]
    bitpos = 0
    data = s[1:]
    for j in range(1, n):
        for i in range(j):
            if (data[bitpos // 6] - 63) >> (5 - bitpos % 6) & 1:
                adj[i].append(j)
                adj[j].append(i)
            bitpos += 1
    return n, adj


def components_of_size(m: int, dlo: int, dhi: int) -> list[tuple[int, list[list[int]]]]:
    if m < dlo + 1:
        return []
    out = []
    proc = subprocess.run([GENG, "-cq", f"-d{dlo}", f"-D{dhi}", str(m)],
                          capture_output=True)
    for line in proc.stdout.split():
        out.append(parse_g6(line))
    return out


def exact_counts(n: int, adj: list[list[int]]):
    """(card type count, orbit count) via pynauty, exact."""
    certs = set()
    for v in range(n):
        vertices = [u for u in range(n) if u != v]
        relabel = {u: i for i, u in enumerate(vertices)}
        g = pynauty.Graph(number_of_vertices=n - 1, directed=False,
                          adjacency_dict={relabel[u]: [relabel[w] for w in adj[u] if w != v]
                                          for u in vertices})
        certs.add(pynauty.certificate(g))
    g = pynauty.Graph(number_of_vertices=n, directed=False,
                      adjacency_dict={v: adj[v] for v in range(n)})
    return len(certs), pynauty.autgrp(g)[4]


def unions(n: int, dlo: int, dhi: int):
    """Yield all disconnected graphs on n vertices with degrees in [dlo,dhi]
    as adjacency lists (disjoint unions of >= 2 connected components)."""
    minc = dlo + 1
    pool: dict[int, list] = {m: components_of_size(m, dlo, dhi)
                             for m in range(minc, n - minc + 1)}

    def partitions(total: int, maxpart: int):
        if total == 0:
            yield []
            return
        for p in range(min(total, maxpart), minc - 1, -1):
            if total - p != 0 and total - p < minc:
                continue
            for rest in partitions(total - p, p):
                yield [p] + rest

    for part in partitions(n, n - minc):
        if len(part) < 2:
            continue
        # multiset of components per size, combinations with replacement
        from collections import Counter
        sizes = Counter(part)
        choices_per_size = []
        ok = True
        for m, cnt in sizes.items():
            comps = pool.get(m, [])
            if not comps:
                ok = False
                break
            choices_per_size.append(
                list(itertools.combinations_with_replacement(range(len(comps)), cnt)))
        if not ok:
            continue
        size_list = list(sizes.keys())
        for combo in itertools.product(*choices_per_size):
            adj = []
            offset = 0
            for m, picks in zip(size_list, combo):
                for idx in picks:
                    cn, cadj = pool[m][idx]
                    adj.extend([x + offset for x in row] for row in cadj)
                    offset += cn
            yield offset, adj


def main() -> None:
    slices = [("reg", d, d, n) for n in (13, 14) for d in range(2, (n - 1) // 2 + 1)]
    slices += [("win", a, a + 1, 13) for a in range(2, 6)]
    total = witnesses = 0
    for kind, dlo, dhi, n in slices:
        cnt = 0
        for m, adj in unions(n, dlo, dhi):
            cnt += 1
            k, orbits = exact_counts(m, adj)
            if k in (2, 3) and orbits > k:
                witnesses += 1
                print(f"WITNESS-COMPLEMENT {kind} n={n} d=[{dlo},{dhi}] "
                      f"cardtypes={k} orbits={orbits}", flush=True)
        print(f"slice {kind} n={n} d=[{dlo},{dhi}]: {cnt} disconnected unions tested",
              flush=True)
        total += cnt
    print(f"GAPCLOSE DONE unions={total} witnesses={witnesses}")


if __name__ == "__main__":
    main()
